// Generates packaging/embedded-assets.ts: file-attribute imports for every
// file in the SvelteKit client build, so `bun build --compile` embeds them
// all into the executable and they can be served from memory at runtime.
import { readdirSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const roots = ["client", "prerendered"].filter((name) => {
    try {
        return readdirSync(join(import.meta.dir, "..", "build", name)).length >= 0;
    } catch {
        return false;
    }
});

function walk(dir: string, out: string[]): void {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const abs = join(dir, entry.name);
        if (entry.isDirectory()) {
            walk(abs, out);
        } else if (entry.isFile()) {
            out.push(abs);
        }
    }
}

const files: string[] = [];
for (const root of roots) {
    walk(join(import.meta.dir, "..", "build", root), files);
}

// Deterministic order for reproducible builds.
files.sort();

const imports: string[] = [];
const entries: string[] = [];

files.forEach((abs, i) => {
    const rel = relative(join(import.meta.dir, "..", "build"), abs).split(sep).join("/");
    const root = rel.split("/")[0];
    const webPath = "/" + rel.slice(root.length + 1);
    imports.push(`import a${i} from "../build/${rel}" with { type: "file" };`);
    entries.push(`    ["${webPath}", a${i}]`);
});

const out = `// GENERATED by generate-embedded-assets.ts — do not edit.
// Maps web paths (as served by the app) to embedded file paths inside the
// compiled executable.

${imports.join("\n")}

export const embeddedAssets = new Map<string, string>([
${entries.join(",\n")}
]);
`;

writeFileSync(join(import.meta.dir, "embedded-assets.ts"), out);
console.log(`embedded-assets.ts: ${files.length} files (${roots.join(", ")})`);
